language: node_js
node_js:
  - "8"
  - "10"
sudo: false
script: "gulp test && gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
